In deze opgave classificeren afbeeldingen van bloemen uit de iris dataset met behulp van een neuraal netwerk.

In [391]:
import numpy as np

import ssl
##om ssl-certificering te omzeilen
#ssl._create_default_https_context = ssl._create_unverified_context

import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

Laad de dataset en maak een feature matrix X en een target vector y.

In [392]:
iris = sns.load_dataset('iris')

# we gebruiken .values om een Numpy array te krijgen in plaats van een Pandas DataFrame
X_iris = iris.drop('species', axis=1).values 
y_iris = iris['species'].values

In [393]:
y_iris = y_iris.reshape(-1, 1) # maak een array van array's, dit is nodig voor de volgende stap
print(y_iris[:10])

[['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']
 ['setosa']]


Een neuraal netwerk kan niet omgaan met categorische labels zoals de namen van de planten, maar heeft getallen als uitput nodig. We hebben hier drie klassen (setosa, versicolor, virginica) daarom maken we een target vector met per label drie waarden. Een 1 voor de eerste waarde correspondeert met 'setosa', een 1 voor de 2e waade met 'versicolor' en een 1 voor de derde waarde met 'virginica'.

Doe dit met behulp van het `OneHotEncoder` object uit sklearn.

In [394]:
# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
y_iris = pd.DataFrame(enc.fit_transform(y_iris).toarray()).values

y_iris


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

We hebben de data nu in een geschikt formaat. Splits de data in training en test data.

In [395]:
X_train, X_test, y_train, y_test = train_test_split(X_iris, y_iris, test_size= 0.2, random_state=6)

Maak een eenvoudig neuraal netwerk met 3 lagen, waarin elke neuron in een laag met elk neuron in de vorige laag verbonden is ('Dense'). 
Voeg voor de eeste laag een parameter `input_shape` toe die aangeeft hoeveel features een element in 'X' heeft.
Het aantal neuronen in de laaste laag is gelijk aan het aantal waarden in een label in `y`. 

In [396]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(units=4, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=y_train.shape[1], activation='softmax'))

#voeg lagen toe met model.add()


Compileer en bekijk het netwerk door onderstaande code te runnen.

Keras uitleg:
https://www.oreilly.com/content/getting-started-with-deep-learning-using-keras-and-python/

Maakt het uit hoeveel units je zet bij input layer?
- JA de uitkomsten varieren heel erg

The input layer is the first layer of the neural network, and its role is to receive the input data and pass it forward to the next layer (i.e., the first hidden layer). The number of units in the input layer is determined by the number of features in the input data.

Changing the number of units in the input layer will not affect the model's performance, since the input layer is just a "pass-through" layer that does not perform any computation.

On the other hand, the hidden layers are where most of the computation and feature extraction happens. Each unit in a hidden layer receives inputs from all the units in the previous layer, and computes a weighted sum of these inputs followed by an activation function.

Changing the number of units in the hidden layers can have a significant impact on the model's performance. Increasing the number of units in a hidden layer can increase the model's capacity to learn complex representations of the input data, but it also increases the risk of overfitting if the model becomes too complex. Decreasing the number of units can reduce the model's capacity, which may limit its ability to capture important patterns in the data.

In summary, changing the number of units in the input layer will not affect the model's performance, while changing the number of units in the hidden layers can have a significant impact on the model's capacity and ability to learn important patterns in the data.

In [397]:
from keras.optimizers import Adam

model.compile(Adam(lr=0.01),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential_38"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_95 (Dense)            (None, 4)                 20        
                                                                 
 dense_96 (Dense)            (None, 32)                160       
                                                                 
 dense_97 (Dense)            (None, 3)                 99        
                                                                 
Total params: 279
Trainable params: 279
Non-trainable params: 0
_________________________________________________________________


Nu kunnen we ons model trainen met behulp van de `fit` methode.

In [398]:
model.fit(X_train, y_train, epochs = 25, batch_size = 5)

Epoch 1/25
24/24 [==============================] - 0s 453us/step - loss: 0.7600 - accuracy: 0.6667
Epoch 2/25
24/24 [==============================] - 0s 363us/step - loss: 0.4889 - accuracy: 0.6750
Epoch 3/25
24/24 [==============================] - 0s 404us/step - loss: 0.4184 - accuracy: 0.7833
Epoch 4/25
24/24 [==============================] - 0s 397us/step - loss: 0.2421 - accuracy: 0.9333
Epoch 5/25
24/24 [==============================] - 0s 386us/step - loss: 0.2984 - accuracy: 0.8667
Epoch 6/25
24/24 [==============================] - 0s 376us/step - loss: 0.1429 - accuracy: 0.9583
Epoch 7/25
24/24 [==============================] - 0s 374us/step - loss: 0.2144 - accuracy: 0.8833
Epoch 8/25
24/24 [==============================] - 0s 373us/step - loss: 0.1743 - accuracy: 0.9167
Epoch 9/25
24/24 [==============================] - 0s 405us/step - loss: 0.1169 - accuracy: 0.9417
Epoch 10/25
24/24 [==============================] - 0s 377us/step - loss: 0.1210 - accuracy: 0.9500

Met `model_evaluate` kunnen we bepalen hoe goed het model werkt op de test data.

In [399]:
test_loss, test_acc = model.evaluate(X_test, y_test)
print(test_acc)

1/1 [==============================] - 0s 64ms/step - loss: 0.1108 - accuracy: 0.9667
0.9666666388511658


Experimenteer met bovenstaand model. Wat gebeurt er als je meer lagen toevoegt of een laag weghaalt of het aantal neuronen in een laag verandert? 

Probeer ook eens andere activatiefuncties dan `relu`, zoals `tanh` of `sigmoid`.

Welke invloed heeft het aantal epochs?
Het zorgt voor de aantal keren dat de training data word bekeken tijdens het trainings process. 
Het omlaag doen van de epoch kan ervoor zorgen dat het model niet volledig alle patronen uit de data zal leren.


In each epoch, the model will update its internal parameters based on the input data and the loss function, with the aim of minimizing the difference between the predicted and actual output.

We kunnen dezelfde aanpak gebruiken voor andere data, bijvoorbeeld voor het herkennen van cijfers. We gebruiken de `MNist` dataset die bestaat uit plaatjes van cijfers. Ieder plaatje bestaat uit 28 x 28 pixels.

In [400]:
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

import warnings
warnings.filterwarnings('ignore')

In [401]:
train_images.shape

(60000, 28, 28)

In [402]:
len(train_labels)

60000

In [403]:
print(train_labels)

[5 0 4 ... 5 6 8]


Een eenvoudig neuraal netwerk heeft een array van inputwaarden nodig i.p.v. een 2D afbeelding.
We maken van de inputs (waarden tussen 0 en 255) getallen tussen 0 en 1.

In [404]:
train_images = train_images.reshape((60000, 28 * 28)) # lijst van waarden i.p.v. 2D afbeelding
train_images = train_images.astype('float32') / 255 # getallen tussen 0 en 1

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

Voor elk label (een cijfer) maken we een array met 10 waarden: 9 nullen en een één, waarbij de positie van de één aangeeft om welk cijfer het gaat (One hot encoding). Dit keer gebruiken we hiervoor de `keras` functie `to_categorical`.

In [405]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

print(train_labels)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


Maak nu een neuraal netwerk met twee lagen, een eerste laag met 512 neuronen en een output laag met 10 neuronen. Geef bij de eerste laag aan hoeveel inputs er zijn en wat de activatiefunctie is. De output laag heeft een `softmax` activatiefunctie.

In [406]:
model2 = Sequential()
model2.add(Dense(units=512, activation='relu', input_shape=(train_images.shape[1],)))
model2.add(Dense(units=10, activation='softmax'))

compileer het netwerk.

In [407]:

model2.compile(Adam(lr=0.01),'categorical_crossentropy',metrics=['accuracy'])

model2.summary()


Model: "sequential_39"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_98 (Dense)            (None, 512)               401920    
                                                                 
 dense_99 (Dense)            (None, 10)                5130      
                                                                 
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


train het netwerk 5 epochs met een batch_size van 128.

In [410]:
model2.fit(train_images, train_labels, epochs = 5, batch_size = 128)

Epoch 1/5
469/469 [==============================] - 1s 2ms/step - loss: 0.1625 - accuracy: 0.9613
Epoch 2/5
469/469 [==============================] - 1s 2ms/step - loss: 0.1249 - accuracy: 0.9669
Epoch 3/5
469/469 [==============================] - 1s 2ms/step - loss: 0.1112 - accuracy: 0.9690
Epoch 4/5
469/469 [==============================] - 1s 2ms/step - loss: 0.1033 - accuracy: 0.9709
Epoch 5/5
469/469 [==============================] - 1s 2ms/step - loss: 0.0973 - accuracy: 0.9722


Evalueer het netwerk op de test set.

In [409]:
test_loss, test_acc = model2.evaluate(test_images, test_labels)
print(test_acc)

313/313 [==============================] - 0s 586us/step - loss: 0.3516 - accuracy: 0.9487
0.9487000107765198


Experimenteer met verschillende netwerken. Varieer het aantal lagen, het aantal neuronen, de activatiefunties en het aantal epochs.