In [73]:
import numpy as np

input_nodes = 3
hidden_nodes = 3
output_nodes = 3

def check(x):
    return (x>0) * x

def make_weights(nr_neurons, inputs):
    return np.random.rand(nr_neurons, inputs) - 0.5
    
def make_biases(nr_neurons):
    return np.random.rand(nr_neurons, 1)

def feed_forward(layer, input_data):
   result = layer['weights'] @ input_data + layer['biases']
   result = layer['actief'](result)
   return  result

def Dense(nr_neurons, inputs, actif):
    W = check(make_weights(nr_neurons,inputs))
    B = check(make_biases(nr_neurons))
    return {"weights": W, "biases": B, "actief": actif}

W = check(make_weights(3,2))
B = check(make_biases(2))
Layer = Dense(3,2,check)

feed_forward(Layer, B)








array([[0.93276101],
       [0.89508859],
       [0.8909408 ]])

Een @ is ee nmatrix vermeningvuldiging

## __init__(self, inputnodes, hiddennodes, outputnodes, learningrate)
This method is the constructor of the neuralNetwork class, which is called when you create a new instance of the class. It takes four arguments:

- inputnodes: The number of nodes in the input layer of the neural network.
- hiddennodes: The number of nodes in the hidden layer of the neural network.
- outputnodes: The number of nodes in the output layer of the neural network.
- learningrate: The learning rate of the neural network, which controls how quickly the network adapts to new data.

## train(self, inputs_list, targets_list)
This method is used to train the neural network on a given set of inputs and targets. It takes two arguments:

- inputs_list: A list of input values.
- targets_list: A list of target values.

## query(self, inputs_list)
This method is used to get the output of the neural network for a given set of inputs. It takes one argument:

- inputs_list: A list of input values.

In [74]:
from scipy.special import expit
import numpy as np

class neuralNetwork:
    """
    The __init__ method initializes the neural network by setting the number of nodes in each layer, generating random weights for the connections between the input and hidden layers (wih) and the hidden and output layers (who), and setting the activation function to the sigmoid function.
    """
    def __init__(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        self.inodes = input_nodes
        self.hnodes = hidden_nodes
        self.onodes = output_nodes
        self.wih = np.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        self.who = np.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))
        self.lr = learning_rate
        self.activation_function = expit

    """
    The train method first converts the input and target lists to 2D numpy arrays and transposes them. It then calculates the output of the neural network for the given inputs, calculates the error between the output and the targets, and backpropagates the error through the network to update the weights.
    """
    def train(self, inputs_list, targets_list):
        inputs = np.array(inputs_list, ndmin=2).T
        targets = np.array(targets_list, ndmin=2).T
        hidden_inputs = self.wih.dot(inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        final_inputs = self.who.dot(hidden_outputs)
        final_outputs = self.activation_function(final_inputs)
        output_errors = targets - final_outputs
        hidden_errors = self.who.T.dot(output_errors)
        self.who += self.lr * (output_errors * final_outputs * (1.0 - final_outputs)) @ hidden_outputs.T
        self.wih += self.lr * (hidden_errors * hidden_outputs * (1.0 - hidden_outputs)) @ inputs.T

    """
    The method first converts the input list to a 2D numpy array and transposes it. It then calculates the output of the neural network for the given inputs and returns it.
    """
    def query(self, inputs_list):
        inputs = np.array(inputs_list, ndmin=2).T
        hidden_inputs = self.wih.dot(inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        final_inputs = self.who.dot(hidden_outputs)
        final_outputs = self.activation_function(final_inputs)
        return final_outputs


In [75]:
# number of input, hidden and output nodes
input_nodes = 3
hidden_nodes = 3
output_nodes = 3

# learning rate is 0.3
learning_rate = 0.3

# create instance of neural network
n = neuralNetwork(input_nodes,hidden_nodes,output_nodes, learning_rate)

In [76]:
# test query (doesn't mean anything useful yet)
n.query([1.0, 0.5, -1.5])

array([[0.54440149],
       [0.6428091 ],
       [0.28394414]])

In [1]:
import numpy as np

class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size

        # Initialize weights
        self.W1 = np.random.randn(self.input_size, self.hidden_size)
        self.b1 = np.zeros((1, self.hidden_size))
        self.W2 = np.random.randn(self.hidden_size, self.output_size)
        self.b2 = np.zeros((1, self.output_size))

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def forward(self, X):
        # Forward propagation
        self.z1 = np.dot(X, self.W1) + self.b1
        self.a1 = self.sigmoid(self.z1)
        self.z2 = np.dot(self.a1, self.W2) + self.b2
        self.a2 = self.sigmoid(self.z2)
        return self.a2

    def backward(self, X, y, learning_rate):
        m = X.shape[0]  # number of samples

        # Backward propagation
        self.dz2 = self.a2 - y
        self.dW2 = (1 / m) * np.dot(self.a1.T, self.dz2)
        self.db2 = (1 / m) * np.sum(self.dz2, axis=0, keepdims=True)
        self.dz1 = np.dot(self.dz2, self.W2.T) * self.a1 * (1 - self.a1)
        self.dW1 = (1 / m) * np.dot(X.T, self.dz1)
        self.db1 = (1 / m) * np.sum(self.dz1, axis=0, keepdims=True)

        # Gradient descent parameter update
        self.W2 -= learning_rate * self.dW2
        self.b2 -= learning_rate * self.db2
        self.W1 -= learning_rate * self.dW1
        self.b1 -= learning_rate * self.db1

    def train(self, X, y, epochs, learning_rate):
        for epoch in range(epochs):
            # Forward and backward pass
            output = self.forward(X)
            self.backward(X, y, learning_rate)

            # Print loss every 100 epochs
            if (epoch + 1) % 100 == 0:
                loss = np.mean(np.square(output - y))
                print(f"Epoch {epoch + 1}/{epochs}, Loss: {loss:.4f}")

    def predict(self, X):
        return self.forward(X)


In [2]:
# Create a neural network with 2 input units, 3 hidden units, and 1 output unit
nn = NeuralNetwork(2, 3, 1)

# Generate some random training data
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Train the neural network
nn.train(X, y, epochs=1000, learning_rate=0.1)

# Make predictions on new data
new_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
predictions = nn.predict(new_data)
print("Predictions:")
print(predictions)


Epoch 100/1000, Loss: 0.2504
Epoch 200/1000, Loss: 0.2499
Epoch 300/1000, Loss: 0.2495
Epoch 400/1000, Loss: 0.2491
Epoch 500/1000, Loss: 0.2485
Epoch 600/1000, Loss: 0.2479
Epoch 700/1000, Loss: 0.2470
Epoch 800/1000, Loss: 0.2459
Epoch 900/1000, Loss: 0.2445
Epoch 1000/1000, Loss: 0.2426
Predictions:
[[0.51632765]
 [0.48755879]
 [0.52068837]
 [0.45971085]]
